### ISSUE TITLE
MongoDB 3.4 Support

### ISSUE THREAD

**Issue by simsekgokhan** [Studio3T/robomongo#1250]
**Robomongo 1.1 - Beta version with MongoDB 3.4 Support is released in the link below:**
https://github.com/Studio3T/robomongo/issues/1250#issuecomment-301036770

Transition to mongodb 3.4 drivers. 
https://github.com/mongodb/mongo/tree/r3.4.0

**Comment by robertzml** [comment]
Will the decimal type support in Robomongo 1.0?

**Comment by simsekgokhan** [comment]
Hi @robertzml , most probably. We are very close to publish a new release in a week.
After that, we plan to put our focus on all 3.4 support and we will keep your question in mind. I think the answer will be clear when we start 3.4 support development. Best Regards.

**Comment by simsekgokhan** [comment]
**Update:** 
Currently, development version can connect and do basic operations with Mongo Atlas 3.4 free cluster (SSL), local 3.4 without SSL and SSH on cross plaftorms. Decimal version is also implemented. 

**Next Actions:**
- Verify all operations working after 3.4 transition.  
- Verify critical features such as Replica Set, SSL, SSH are working cross plaftorm.
- Verify NumberDecimal type is working correctly

**ETA:** 
2-3 weeks

**Comment by simsekgokhan** [comment]
Hi All, we decided to make a beta release available both for testing and to make connections to Mongo Atlas 3.4 free cluster available immediately. Please share your problems during this beta testing period.

Please see the beta installers and details here:  
[Robomongo 1.1 - Beta version with MongoDB 3.4 Support](https://github.com/Studio3T/robomongo/releases/tag/v1.1.0-beta)


**Next Actions:**
- Complete QA testing
- Release non-beta version 1.1 

**ETA of new release 1.1**
6-June-2017

**Comment by danafreer** [comment]
Superb! 
I have installed 1,1 Beta - and at last connected to Altlas 3.4. Great!
Will test, and let you know any problems.
Thanks!

**Comment by edgareler** [comment]
I confirm that this `v1.1.0-beta` it is working for my two Atlas 3.4 clusters.

**Comment by ssmlee04** [comment]
When I am trying to check the collection indexes it gives the following errors:

```
Cannot load list of indexes.

Error:
NsToCollectionSubstring: no 
```

![https://i.stack.imgur.com/CiWjD.png](https://i.stack.imgur.com/CiWjD.png)

**Comment by simsekgokhan** [comment]
Hi @ssmlee04 , thanks for reporting the problem. We will investigate.

@danafreer , @edgareler , could you share your OS versions? Thanks a lot.

**Comment by danafreer** [comment]
Yes I see the same problem when attempting to list indexes.

I am on Windows 10.

**Comment by edgareler** [comment]
@simsekgokhan, I'm using Ubuntu 16.04 amd64.

I got the same issue on listing indexes. You can see the log below:

```
2017-05-15T08:43:56.053-0300 I -        [thread2] Assertion: 16886:nsToCollectionSubstring: no . src/mongo/db/namespace_string.h 362
2017-05-15T08:43:56.059-0300 I CONTROL  [thread2] 
 0xd5e482 0xcec292 0x81a60f 0xa71e99 0xa6cd47 0x8be5b5 0x8c59ce 0x7fb676d2625a 0x7fb676d2b391 0x869e1a 0x7fb677ac152c 0x7fb677ac8220 0x7fb676d1bae0 0x7fb676d1e51b 0x7fb676d68c53 0x7fb6726a8197 0x7fb6726a83f0 0x7fb6726a849c 0x7fb676d69047 0x7fb676d19dca 0x7fb676b50f1c 0x7fb676b555f9 0x7fb67580c6ba 0x7fb67554282d
----- BEGIN BACKTRACE -----
{"backtrace":[{"b":"400000","o":"95E482","s":"_ZN5mongo15printStackTraceERSo"},{"b":"400000","o":"8EC292","s":"_ZN5mongo10logContextEPKc"},{"b":"400000","o":"41A60F","s":"_ZN5mongo23msgassertedWithLocationEiPKcS1_j"},{"b":"400000","o":"671E99","s":"_ZN5mongo23nsToCollectionSubstringENS_10StringDataE"},{"b":"400000","o":"66CD47","s":"_ZN5mongo20DBClientWithCommands13getIndexSpecsERKSsi"},{"b":"400000","o":"4BE5B5","s":"_ZNK9Robomongo11MongoClient10getIndexesERKNS_19MongoCollectionInfoE"},{"b":"400000","o":"4C59CE","s":"_ZN9Robomongo11MongoWorker6handleEPNS_28LoadCollectionIndexesRequestE"},{"b":"7FB676AAA000","o":"27C25A","s":"_ZNK11QMetaMethod6invokeEP7QObjectN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS5_S5_S5_S5_S5_S5_S5_S5_S5_"},{"b":"7FB676AAA000","o":"281391","s":"_ZN11QMetaObject12invokeMethodEP7QObjectPKcN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS7_S7_S7_S7_S7_S7_S7_S7_S7_"},{"b":"400000","o":"469E1A","s":"_ZN9Robomongo18EventBusDispatcher5eventEP6QEvent"},{"b":"7FB67796D000","o":"15452C","s":"_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent"},{"b":"7FB67796D000","o":"15B220","s":"_ZN12QApplication6notifyEP7QObjectP6QEvent"},{"b":"7FB676AAA000","o":"271AE0","s":"_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent"},{"b":"7FB676AAA000","o":"27451B","s":"_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData"},{"b":"7FB676AAA000","o":"2BEC53"},{"b":"7FB67265E000","o":"4A197","s":"g_main_context_dispatch"},{"b":"7FB67265E000","o":"4A3F0"},{"b":"7FB67265E000","o":"4A49C","s":"g_main_context_iteration"},{"b":"7FB676AAA000","o":"2BF047","s":"_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE"},{"b":"7FB676AAA000","o":"26FDCA","s":"_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE"},{"b":"7FB676AAA000","o":"A6F1C","s":"_ZN7QThread4execEv"},{"b":"7FB676AAA000","o":"AB5F9"},{"b":"7FB675805000","o":"76BA"},{"b":"7FB67543C000","o":"10682D","s":"clone"}],"processInfo":{ "mongodbVersion" : "3.4.3-7-gf394f8c", "gitVersion" : "f394f8c348cf755274e6d1c8abb50335f13c3df3", "compiledModules" : [], "uname" : { "sysname" : "Linux", "release" : "4.9.9-040909-generic", "version" : "#201702090333 SMP Thu Feb 9 08:35:27 UTC 2017", "machine" : "x86_64" }, "somap" : [ { "elfType" : 2, "b" : "400000", "buildId" : "FF62D400D3805A8FCC6D445014C089F9559E0D40" }, { "b" : "7FFEEEF01000", "elfType" : 3, "buildId" : "C533068777A1E0BFC96D8236A75ECD89F95330F2" }, { "b" : "7FB6781BC000", "path" : "/path/to/robomongo/bin/../lib/libQt5Network.so.5", "elfType" : 3, "buildId" : "24F4C48F8659E13C5BE1B3FB17F8C90CF64179FA" }, { "b" : "7FB67796D000", "path" : "/path/to/robomongo/bin/../lib/libQt5Widgets.so.5", "elfType" : 3, "buildId" : "C59F1F41B993B45E7D3C2A69EDB2BF1749FC6D0B" }, { "b" : "7FB6771C5000", "path" : "/path/to/robomongo/bin/../lib/libQt5Gui.so.5", "elfType" : 3, "buildId" : "35F538630D3D7594750BC20901F707FD56D2FF07" }, { "b" : "7FB676AAA000", "path" : "/path/to/robomongo/bin/../lib/libQt5Core.so.5", "elfType" : 3, "buildId" : "8B9BD3D03EC7B5DE0FFC4D769D84AD40FA07B45C" }, { "b" : "7FB6768A6000", "path" : "/lib/x86_64-linux-gnu/libdl.so.2", "elfType" : 3, "buildId" : "C0C5B7F18348654040534B050B110D32A19EA38D" }, { "b" : "7FB67663F000", "path" : "/path/to/robomongo/bin/../lib/libssl.so.1.0.0", "elfType" : 3, "buildId" : "30BFBE59FAB966BE5653097E5E7C45035C3BEA7B" }, { "b" : "7FB676253000", "path" : "/path/to/robomongo/bin/../lib/libcrypto.so.1.0.0", "elfType" : 3, "buildId" : "B9B011055EFD5210434E0AB6D6F616EA41E36932" }, { "b" : "7FB675F41000", "path" : "/path/to/robomongo/bin/../lib/libstdc++.so.6", "elfType" : 3, "buildId" : "20B4B3F6249A83E53E9EF908355D2BBA9C61687D" }, { "b" : "7FB675C38000", "path" : "/lib/x86_64-linux-gnu/libm.so.6", "elfType" : 3, "buildId" : "05451CB4D66C321691F64F253880B7CE5B8812A6" }, { "b" : "7FB675A22000", "path" : "/lib/x86_64-linux-gnu/libgcc_s.so.1", "elfType" : 3, "buildId" : "68220AE2C65D65C1B6AAA12FA6765A6EC2F5F434" }, { "b" : "7FB675805000", "path" : "/lib/x86_64-linux-gnu/libpthread.so.0", "elfType" : 3, "buildId" : "84538E3C6CFCD5D4E3C0D2B6C3373F802915A498" }, { "b" : "7FB67543C000", "path" : "/lib/x86_64-linux-gnu/libc.so.6", "elfType" : 3, "buildId" : "CBFA941A8EB7A11E4F90E81B66FCD5A820995D7C" }, { "b" : "7FB675222000", "path" : "/lib/x86_64-linux-gnu/libz.so.1", "elfType" : 3, "buildId" : "340B7B463F981B8A0FB3451751F881DF1B0C2F74" }, { "b" : "7FB674FAE000", "path" : "/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1", "elfType" : 3, "buildId" : "DAD757CF9419D0FEA30E5994E377C95240F6CB9C" }, { "b" : "7FB674B14000", "path" : "/path/to/robomongo/bin/../lib/libicui18n.so.56", "elfType" : 3, "buildId" : "ECB6086986AC5E984641DD02D4163BB52E012A54" }, { "b" : "7FB67475C000", "path" : "/path/to/robomongo/bin/../lib/libicuuc.so.56", "elfType" : 3, "buildId" : "99B9B7C1E0956CF7BB607317E394C51E799697AF" }, { "b" : "7FB672D79000", "path" : "/path/to/robomongo/bin/../lib/libicudata.so.56", "elfType" : 3, "buildId" : "EB49B3BDD1947322FDB3B6C56F987F09881986AF" }, { "b" : "7FB672B77000", "path" : "/usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0", "elfType" : 3, "buildId" : "21CC52ECF5DFE2B9D60EAA1C7DEB93B4B1B86588" }, { "b" : "7FB67296F000", "path" : "/lib/x86_64-linux-gnu/librt.so.1", "elfType" : 3, "buildId" : "0DBB8C21FC5D977098CA718BA2BFD6C4C21172E9" }, { "b" : "7FB67265E000", "path" : "/lib/x86_64-linux-gnu/libglib-2.0.so.0", "elfType" : 3, "buildId" : "47D9CF982A9E8208BBF13E2786D26B1B65D14723" }, { "b" : "7FB67851A000", "path" : "/lib64/ld-linux-x86-64.so.2", "elfType" : 3, "buildId" : "A7D5A820B802049276B1FC26C8E845A3E194EB6B" }, { "b" : "7FB672435000", "path" : "/lib/x86_64-linux-gnu/libexpat.so.1", "elfType" : 3, "buildId" : "31189115AEDE28AA249FF039765C2A7BCBEB1FAA" }, { "b" : "7FB672232000", "path" : "/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0", "elfType" : 3, "buildId" : "46A1ABF8A63838FF99B1B9A470B10E78C7338B3F" }, { "b" : "7FB67202F000", "path" : "/usr/lib/x86_64-linux-gnu/libxcb-present.so.0", "elfType" : 3, "buildId" : "DC6834C8AD2DE7E22E31D80DAD3E82DDB30E7C3C" }, { "b" : "7FB671E28000", "path" : "/usr/lib/x86_64-linux-gnu/libxcb-sync.so.1", "elfType" : 3, "buildId" : "4D1DA1B786B710B459007400247B7D1B132EDDD8" }, { "b" : "7FB671C25000", "path" : "/usr/lib/x86_64-linux-gnu/libxshmfence.so.1", "elfType" : 3, "buildId" : "743C1A1ACD5F738609AFCA476ECC988F8D62D569" }, { "b" : "7FB6719F6000", "path" : "/usr/lib/x86_64-linux-gnu/libglapi.so.0", "elfType" : 3, "buildId" : "54EBBE67F82A0DDB530B3236B22A9044C6358B3C" }, { "b" : "7FB6717E4000", "path" : "/usr/lib/x86_64-linux-gnu/libXext.so.6", "elfType" : 3, "buildId" : "EC7DDBE21EA0DE71BA48AD4D2402042654DE5A88" }, { "b" : "7FB6715E1000", "path" : "/usr/lib/x86_64-linux-gnu/libXdamage.so.1", "elfType" : 3, "buildId" : "3AE36AE772FDE17E9B66FF36238466B7B81D6E27" }, { "b" : "7FB6713DB000", "path" : "/usr/lib/x86_64-linux-gnu/libXfixes.so.3", "elfType" : 3, "buildId" : "E34CE899AD70F7CB95E2582B6624076105330451" }, { "b" : "7FB6711D9000", "path" : "/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1", "elfType" : 3, "buildId" : "D27D9ACA9F04D56FBF904659322971B10C0C44D5" }, { "b" : "7FB670E9F000", "path" : "/usr/lib/x86_64-linux-gnu/libX11.so.6", "elfType" : 3, "buildId" : "00DF13B755BE05E7D457E3668E25A0AD069EC79C" }, { "b" : "7FB670C86000", "path" : "/usr/lib/x86_64-linux-gnu/libxcb-glx.so.0", "elfType" : 3, "buildId" : "A1BFEEB52762EB3D914F4F34A30E0C0A8881C315" }, { "b" : "7FB670A81000", "path" : "/usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0", "elfType" : 3, "buildId" : "EBA7360889D269BE064ACA30698234A620BDC0CE" }, { "b" : "7FB67085F000", "path" : "/usr/lib/x86_64-linux-gnu/libxcb.so.1", "elfType" : 3, "buildId" : "64EB2317EF4280CB61853CA6FD8714643BABA1E3" }, { "b" : "7FB670659000", "path" : "/usr/lib/x86_64-linux-gnu/libXxf86vm.so.1", "elfType" : 3, "buildId" : "171D44A2A7FCDD05ABA273A69BE3D846308ABAA0" }, { "b" : "7FB67044A000", "path" : "/usr/lib/x86_64-linux-gnu/libdrm.so.2", "elfType" : 3, "buildId" : "AB87C4D818B66B0ACBC0CDF621159DE0A4B6E39E" }, { "b" : "7FB6701D8000", "path" : "/lib/x86_64-linux-gnu/libpcre.so.3", "elfType" : 3, "buildId" : "167D51A2A51E592D1B87BB4CF16444A41F5F464C" }, { "b" : "7FB66FFD4000", "path" : "/usr/lib/x86_64-linux-gnu/libXau.so.6", "elfType" : 3, "buildId" : "474740350E3636B90972AFC5C701D256DE3D0C7D" }, { "b" : "7FB66FDCE000", "path" : "/usr/lib/x86_64-linux-gnu/libXdmcp.so.6", "elfType" : 3, "buildId" : "EFF0E2B82309027DD2FA776589BE046551009806" } ] }}
 robomongo(_ZN5mongo15printStackTraceERSo+0x32) [0xd5e482]
 robomongo(_ZN5mongo10logContextEPKc+0x132) [0xcec292]
 robomongo(_ZN5mongo23msgassertedWithLocationEiPKcS1_j+0x1CD) [0x81a60f]
 robomongo(_ZN5mongo23nsToCollectionSubstringENS_10StringDataE+0x29) [0xa71e99]
 robomongo(_ZN5mongo20DBClientWithCommands13getIndexSpecsERKSsi+0x87) [0xa6cd47]
 robomongo(_ZNK9Robomongo11MongoClient10getIndexesERKNS_19MongoCollectionInfoE+0x95) [0x8be5b5]
 robomongo(_ZN9Robomongo11MongoWorker6handleEPNS_28LoadCollectionIndexesRequestE+0x7E) [0x8c59ce]
 libQt5Core.so.5(_ZNK11QMetaMethod6invokeEP7QObjectN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS5_S5_S5_S5_S5_S5_S5_S5_S5_+0x63A) [0x7fb676d2625a]
 libQt5Core.so.5(_ZN11QMetaObject12invokeMethodEP7QObjectPKcN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS7_S7_S7_S7_S7_S7_S7_S7_S7_+0x981) [0x7fb676d2b391]
 robomongo(_ZN9Robomongo18EventBusDispatcher5eventEP6QEvent+0x1BA) [0x869e1a]
 libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9C) [0x7fb677ac152c]
 libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x3B0) [0x7fb677ac8220]
 libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x100) [0x7fb676d1bae0]
 libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x1CB) [0x7fb676d1e51b]
 libQt5Core.so.5(+0x2BEC53) [0x7fb676d68c53]
 libglib-2.0.so.0(g_main_context_dispatch+0x2A7) [0x7fb6726a8197]
 libglib-2.0.so.0(+0x4A3F0) [0x7fb6726a83f0]
 libglib-2.0.so.0(g_main_context_iteration+0x2C) [0x7fb6726a849c]
 libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x57) [0x7fb676d69047]
 libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0xEA) [0x7fb676d19dca]
 libQt5Core.so.5(_ZN7QThread4execEv+0x8C) [0x7fb676b50f1c]
 libQt5Core.so.5(+0xAB5F9) [0x7fb676b555f9]
 libpthread.so.0(+0x76BA) [0x7fb67580c6ba]
 libc.so.6(clone+0x6D) [0x7fb67554282d]
-----  END BACKTRACE  -----
```

**Comment by simsekgokhan** [comment]
Index problem seems to be fixed, will be available in the official release.

**Comment by ccpalmer** [comment]
I'm trying to use Robomongo to teach here at Dartmouth but it's a large class and the fonts are too small to be seen in the back.  Is there any way to increase the font size???  Otherwise I'll be stuck using inferior tools .

**Comment by zachrattner** [comment]
@ccpalmer Check out this thread - https://github.com/Studio3T/robomongo/issues/645

**Comment by natanrolnik** [comment]
@simsekgokhan is there a Mac version for 1.1 Beta? I can't find it in the [downloads](https://github.com/Studio3T/robomongo/releases/tag/v1.1.0-beta)

**Comment by ccpalmer** [comment]
@zachrattner Thanks, and I've created a robomongo.json file everywhere ;-) but no joy.

```
.config/robomongo//0.9/robomongo.json
.config/robomongo//1.0.0/robomongo.json
.config/robomongo//1.1/robomongo.json
.config/robomongo//1.1.0/robomongo.json
```

with these two font-related lines:

```
"textFontFamily" : "Lucida Console",
"textFontPointSize" : 20,
```

I previously tried "Hack 20" ... and no change no matter what I select.

**Comment by kairsas** [comment]
I get error when expanding "Collections" on mongo 2.6 database:

> Failed to refresh 'Collections'.
> Error:
> ListCollections failed: { ok: 0.0, errmsg: "no such cmd: listCollections", code: 59, bad cmd: { listCollections: 1, filter: {}, cursor: {} } }

**Comment by juliashibalko** [comment]
@kairsas, thanks for reporting very much! We will try to reproduce it and let you know about our results!

**Comment by juliashibalko** [comment]
@kairsas, we see the same problem with mongo v.2.6. Thanks a lot for catchin! We will fix it before the release

**Comment by kairsas** [comment]
Thanks a lot!

**Comment by simsekgokhan** [comment]
Code fixes for list collections and list indexes errors for v2.6 servers added into Robomongo 1.1 official release.

**Comment by juliashibalko** [comment]
Fixed and verified in Robo3T 1.1 version. Closing as fixed.
Please feel free to reopen in any case.

**Comment by vp17in** [comment]
I am using MongoDB 3.4.1 and Robo3T 1.1
I am getting error - Failed to refresh 'Collections'
<img width="576" alt="robo error" src="https://user-images.githubusercontent.com/30339054/28457110-c7518a04-6dfc-11e7-9cf0-befbb516a125.png">

**Comment by gsadhas** [comment]
Hi Team, Thanks for the wonderful tool!

I'm using MongoDB 3.4.1 version and Robo 3T latest version. I cannot connect to MonoDB due to connection failed error. Could you please confirm if Robo 3T latest version is compatible with MongoDB 3.4.1?

Thanks

**Comment by ivorscott** [comment]
I have MongoDB 3.4 and Robomongo 1.1 and I am pretty sure this isn't fixed. I am even using postman and see my api working on the creation on a record outputting the ObjectID with a 200 ok but in Robomongo, although it sees my database, it does not update even after a refresh..

**Comment by menocomp** [comment]
@gsadhas I have the same issue I can not connect to Atlas free cluster although I set connection to be anywhere! Have you found a fix?

**Comment by gsadhas** [comment]
@menocomp Thanks for reaching out to me. Please check your Mongo DB server address and SSH server address. I was using remote server, hence Mongo DB and SSH server have different IP address.
